"""Dump the weather_profile table to a SQL seed file.

Usage:
    python scripts/dump_weather_profile.py

Output:
    scripts/seed_weather_profile.sql

The generated file uses COPY FROM STDIN (much faster than individual INSERTs).
To restore on any Postgres instance:
    psql <connection_string> -f scripts/seed_weather_profile.sql
"""

from __future__ import annotations

import asyncio
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

OUTPUT = Path(__file__).parent / "seed_weather_profile.sql"

DDL = """\
-- Weather profile seed — generated by scripts/dump_weather_profile.py
-- Source: Neon cloud DB, table weather_profile (KNMI station 06280, 30-min slots)

CREATE TABLE IF NOT EXISTS weather_profile (
    timestamp           TIMESTAMPTZ PRIMARY KEY,
    wind_speed_ms       DOUBLE PRECISION,
    wind_dir_deg        DOUBLE PRECISION,
    wind_gust_ms        DOUBLE PRECISION,
    temperature_c       DOUBLE PRECISION,
    air_pressure_hpa    DOUBLE PRECISION,
    humidity_pct        DOUBLE PRECISION,
    radiation_wm2       DOUBLE PRECISION,
    sunshine_min        DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS ix_weather_profile_timestamp ON weather_profile (timestamp);

-- Truncate before re-seeding (idempotent)
TRUNCATE weather_profile;

"""

COPY_HEADER = "COPY weather_profile (timestamp, wind_speed_ms, wind_dir_deg, wind_gust_ms, temperature_c, air_pressure_hpa, humidity_pct, radiation_wm2, sunshine_min) FROM stdin;\n"
COPY_FOOTER = "\\.\n"


def _fmt(v: float | None) -> str:
    """Format a nullable float for COPY text format (\\N for NULL)."""
    return "\\N" if v is None else repr(v)


async def main() -> None:
    try:
        import asyncpg
    except ImportError:
        print("asyncpg not installed — run: pip install asyncpg", file=sys.stderr)
        sys.exit(1)

    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        env_path = Path(__file__).parents[1] / ".env"
        if env_path.exists():
            for line in env_path.read_text().splitlines():
                if line.startswith("DATABASE_URL="):
                    db_url = line.split("=", 1)[1].strip()
                    break
    if not db_url:
        print("DATABASE_URL not found in environment or .env", file=sys.stderr)
        sys.exit(1)

    # asyncpg does not accept ?sslmode= query params — use ssl kwarg instead
    clean_url = db_url.split("?")[0]

    print(f"Connecting to database...")
    conn = await asyncpg.connect(clean_url, ssl="require")

    print("Fetching rows from weather_profile...")
    rows = await conn.fetch(
        "SELECT timestamp, wind_speed_ms, wind_dir_deg, wind_gust_ms, "
        "temperature_c, air_pressure_hpa, humidity_pct, radiation_wm2, sunshine_min "
        "FROM weather_profile ORDER BY timestamp"
    )
    await conn.close()

    print(f"Writing {len(rows)} rows to {OUTPUT}...")
    lines: list[str] = [DDL, COPY_HEADER]
    for row in rows:
        ts = row["timestamp"]
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        ts_str = ts.strftime("%Y-%m-%d %H:%M:%S%z")
        cols = [
            ts_str,
            _fmt(row["wind_speed_ms"]),
            _fmt(row["wind_dir_deg"]),
            _fmt(row["wind_gust_ms"]),
            _fmt(row["temperature_c"]),
            _fmt(row["air_pressure_hpa"]),
            _fmt(row["humidity_pct"]),
            _fmt(row["radiation_wm2"]),
            _fmt(row["sunshine_min"]),
        ]
        lines.append("\t".join(cols) + "\n")
    lines.append(COPY_FOOTER)

    OUTPUT.write_text("".join(lines), encoding="utf-8")

    size_kb = OUTPUT.stat().st_size // 1024
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    print(f"Done — {OUTPUT.name} ({size_kb} KB, {len(rows)} rows, generated {generated_at})")


if __name__ == "__main__":
    asyncio.run(main())
